export const evidence = [
  {
    id: "technology-center",
    kind: "GOVERNMENT",
    title: "湖南省省级企业技术中心",
    en: "Hunan Provincial Enterprise Technology Center",
    text: "2024 年认定名单列明美创数字技术中心，有效期至 2027 年 12 月。",
    enText:
      "Listed in the 2024 provincial recognition, valid through December 2027.",
    source: "湖南省工业和信息化厅",
    date: "2024-11-05",
    level: 1,
    url: "https://gxt.hunan.gov.cn/gxt/xxgk_71033/tzgg/202411/t20241105_33493218.html",
  },
  {
    id: "heritage-standard",
    kind: "STANDARD",
    title: "文物三维扫描建模标准研讨",
    en: "Heritage scanning standard workshop",
    text: "标准发布机构记录美创参与《基于数字赋能文物三维扫描建模技术要求》研讨会。",
    enText:
      "The publisher records MGC's attendance at the scanning and modeling standard workshop.",
    source: "中国国际经济技术合作促进会标准化工作委员会",
    date: "2025-04-18",
    level: 1,
    url: "https://www.capcgbw.com.cn/NewsDetail.aspx?ID=1800",
  },
  {
    id: "public-project",
    kind: "PROJECT",
    title: "《“志”说湖南》布展施工",
    en: "Zhi Shuo Hunan exhibition construction",
    text: "省地方志编纂院成交公告列明美创为布展施工中标供应商。",
    enText:
      "The institution names MGC as the awarded exhibition construction supplier.",
    source: "湖南省地方志编纂院",
    date: "2024-10-11",
    level: 1,
    url: "https://dfz.hunan.gov.cn/dfz/xxgk_71525/tzgg/202410/t20241011_33472794.html",
  },
  {
    id: "scan-patent",
    kind: "PATENT RECORD",
    title: "建筑文物 3D 扫描增强",
    en: "Architectural heritage 3D scan enhancement",
    text: "公开专利文献 CN118761946B，记录申请人为湖南美创数字科技有限公司。",
    enText: "Publication CN118761946B names MGC as the applicant.",
    source: "公开专利文献 / Google Patents",
    date: "2024-12-10",
    level: 2,
    url: "https://patents.google.com/patent/CN118761946B/zh",
  },
  {
    id: "interaction-patent",
    kind: "PATENT RECORD",
    title: "智慧博物馆多维虚拟交互",
    en: "Museum multidimensional virtual interaction",
    text: "公开专利文献 CN119690299B，涉及增强现实场景中的交互资源分配。",
    enText:
      "Publication CN119690299B describes interaction resource allocation in augmented reality.",
    source: "公开专利文献 / Google Patents",
    date: "2025-05-02",
    level: 2,
    url: "https://patents.google.com/patent/CN119690299B/zh",
  },
];
